language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
  fast_finish: true

sudo: false

install:
  - travis_retry composer self-update
  - travis_wait composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit
