language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
  fast_finish: true

sudo: false

install:
  - travis_retry composer self-update
  - travis_wait composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit
